language: python
python:
  - "3.6"
  
# command to install dependencies
install:
  - pip install -r requirements.txt
  
# command to run tests
script:
  - pytest 

# Running coverals

after_success:
  - coveralls