language: python

python:
  - "3.6"
  
env:
  - export FLASK_ENV ="development"
  
# command to install dependencies
install:
  - pip install -r requirements.txt

services:
  - postgresql

before_script:
  - psql -c 'CREATE DATABASE fastfood' -U postgres
    
# command to run tests
script:
  - pytest --cov=app/tests/ 

# Running coverals
after_success:
  - coveralls