language: python

python:
  - "3.6"
  
# command to install dependencies
install:
  - pip install -r requirements.txt

services:
  - postgresql

before_script:
  - psql -c 'CREATE DATABASE fastfood' -U postgres
  - psql -c "CREATE USER andela WITH PASSWORD 'andelan';" -U postgres
    
# command to run tests
script:
  - pytest --cov=app/tests/ 

# Running coverals
after_success:
  - coveralls